### ISSUE TITLE
Zune Social Tagger Crashes immediately

### ISSUE THREAD

**Issue by Firecatman** [leetreveil/Zune-Social-Tagger#1]
As soon as I click on the Zune Social Tagger .exe windows says that it has stopped working, here is the log file http://www.filedropper.com/wer988ftmp
BTW running Win 7 SP1 Beta x64 with .Net 4.0

**Comment by leetreveil** [comment]
I can't open the file, can you either email me it or upload it somewhere else?

**Comment by Firecatman** [comment]
well its a fairly big file for some odd reason 200MB and im not sure where else I can upload it

**Comment by Firecatman** [comment]
heres the dump summary copied to a notepad from VS if that helps http://cid-a140dae1fe047c63.skydrive.live.com/redir.aspx?resid=A140DAE1FE047C63!1307&Bpub=SDX.Docs&Bsrc=GetSharingLink

**Comment by leetreveil** [comment]
Theres nothing I can discern from that, I need a stacktrace really.

**Comment by Firecatman** [comment]
a what

**Comment by Firecatman** [comment]
still have no idea how to get this working

**Comment by leetreveil** [comment]
Fixed.

**Comment by leetreveil** [comment]
Is this error still happening for you?
