### ISSUE TITLE
Something bad happened...

### ISSUE THREAD

**Issue by ctolkien** [leetreveil/Zune-Social-Tagger#10]
When hitting the 'link' button.. stack trace below

Application:       Zune Social Tagger
Version:           2.4.0.0
Date:              30/08/2011 00:29:51
Computer name:     CHADTOLKIEN-PC
User name:         Chad Tolkien
OS:                Microsoft Windows NT 6.1.7601 Service Pack 1
Culture:           en-AU
System up time:    10.13:33:33.5000000
App up time:       00:03:48.0408782
Total memory:      6143Mb
Available memory:  2736Mb

Exception classes:  
   System.IndexOutOfRangeException
Exception messages: 
   Index was outside the bounds of the array.
Stack Traces:
   at ZuneSocialTagger.Core.IO.Mp4Tagger.ZuneXtraParser.getPartName(BinaryReader reader, Int64 length)
   at ZuneSocialTagger.Core.IO.Mp4Tagger.ZuneXtraParser.<ParseXtraAtomRaw>d__d.MoveNext()
   at ZuneSocialTagger.Core.IO.Mp4Tagger.ZuneXtraParser.<ParseRawPartData>d__6.MoveNext()
   at ZuneSocialTagger.Core.IO.Mp4Tagger.ZuneXtraParser.<ParseRawData>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ZuneSocialTagger.Core.IO.Mp4Tagger.ZuneMp4TagContainer.RemoveZuneAttribute(String name)
   at ZuneSocialTagger.GUI.ViewsViewModels.Details.DetailsViewModel.Save()
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
Loaded Modules:
C:\Program Files\Zune\Zune Social Tagger.exe 2.4.0.0
C:\Windows\SYSTEM32\ntdll.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\SYSTEM32\MSCOREE.DLL 4.0.40305.0 (Main.040305-0000)
C:\Windows\system32\KERNEL32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\KERNELBASE.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\ADVAPI32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\msvcrt.dll 7.0.7600.16385 (win7_rtm.090713-1255)
C:\Windows\SYSTEM32\sechost.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\RPCRT4.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll 4.0.30319.1 (RTMRel.030319-0100)
C:\Windows\system32\SHLWAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\GDI32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\USER32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\LPK.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\USP10.dll 1.0626.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\IMM32.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSCTF.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.4940_none_88df89932faf0bf6\MSVCR80.dll 8.00.50727.4940
C:\Windows\system32\shell32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\ole32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\profapi.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\mscorlib\8f7abb6f7384aad8fc43659820726eab\mscorlib.ni.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\system32\CRYPTBASE.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\uxtheme.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System\3e6eefab37b44e147db80a3c34f0ac05\System.ni.dll 2.0.50727.5447 (Win7SP1GDR.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\WindowsBase\64fc9675d94bda9f45731097f140c4f6\WindowsBase.ni.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationCore\72ea2b7db0ac2d9407d8ab2ed257c62a\PresentationCore.ni.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\90e096ee99f6b0760c47016f862cf5a8\PresentationFramework.ni.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\Microsoft.NET\Framework64\v3.0\WPF\wpfgfx_v0300.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\system32\OLEAUT32.dll 6.1.7601.17567
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Core\5f7c48b31971fee1af48dd20c7dd7033\System.Core.ni.dll 3.5.30729.5420 built by: Win7SP1
C:\Windows\system32\dwmapi.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\CRYPTSP.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rsaenh.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\VERSION.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\shfolder.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\df2bfb30ffdbfbb49d2c5ef6fc763578\System.Configuration.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\318b11a6b944c9ef2998d374c9d5bda8\System.Xml.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\system32\urlmon.dll 9.00.8112.16421 (WIN7_IE9_RTM.110308-0330)
C:\Windows\system32\iertutil.dll 9.00.8112.16434 (WIN7_IE9_GDR.110721-1800)
C:\Windows\system32\WININET.dll 9.00.8112.16421 (WIN7_IE9_RTM.110308-0330)
C:\Windows\system32\Normaliz.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WindowsCodecs.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\d3d9.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\d3d8thk.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\aticfx64.dll 8.17.10.1086
C:\Windows\system32\atiu9p64.dll 8.14.01.6221
C:\Windows\system32\atiumd64.dll 7.14.10.0847
C:\Windows\system32\atiumd6a.dll 8.14.10.0316
C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\e197484e00ac02ef81220d0c8b6491e1\PresentationFramework.Aero.ni.dll 3.0.6920.4902 built by: NetFXw7
C:\Windows\system32\WINMM.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\PresentationNative_v0300.dll 3.0.6920.4902 built by: NetFXw7
C:\Windows\system32\CLBCatQ.DLL 2001.12.8530.16385 (win7_rtm.090713-1255)
C:\Windows\system32\RpcRtRemote.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\msctfui.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Seri#\50faf7f472bfc6d562696341df45b3c9\System.Runtime.Serialization.ni.dll 3.0.4506.5420 (Win7SP1.030729-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml.Linq\ebd55d35d25cf10e6e24453238d3c5eb\System.Xml.Linq.ni.dll 3.5.30729.5420 built by: Win7SP1
C:\Windows\system32\rasapi32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rasman.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WS2_32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\NSI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rtutils.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\mswsock.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\wshtcpip.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\wship6.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\winhttp.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\webio.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\IPHLPAPI.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WINNSI.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\dhcpcsvc6.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\dhcpcsvc.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\DNSAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Program Files\Bonjour\mdnsNSP.dll 2.0.4.0
C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDNSP.DLL 7.250.4232.0
C:\Windows\system32\PSAPI.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rasadhlp.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\fwpuclnt.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\security.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\SECUR32.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\SSPICLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\credssp.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\schannel.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\CRYPT32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSASN1.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\assembly\NativeImages_v2.0.50727_64\ZuneDBApi\c91e1c1d8eae60dd340bdbd9b9053395\ZuneDBApi.ni.dll 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorsec.dll 2.0.50727.4927 (NetFXspW7.050727-4900)
C:\Windows\system32\WINTRUST.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.17514_none_a4d6a923711520a9\COMCTL32.dll 5.82 (win7_rtm.090713-1255)
C:\Windows\system32\imagehlp.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\ncrypt.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\bcrypt.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\bcryptprimitives.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\USERENV.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\GPAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\cryptnet.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WLDAP32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\SensApi.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\Cabinet.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\DEVRTL.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Program Files\Zune\ZuneDBApi.dll 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\MSVCR90.dll 9.00.30729.6161
C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251\msvcm90.dll 9.00.30729.6161
C:\Program Files\Zune\ZuneCfg.DLL 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Program Files\Zune\ZuneNativeLib.dll 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_2b24536c71ed437a\gdiplus.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\SETUPAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\CFGMGR32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\DEVOBJ.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\NETAPI32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\netutils.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\srvcli.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\wkscli.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_fa396087175ac9ac\comctl32.dll 6.10 (win7_rtm.090713-1255)
C:\Windows\system32\propsys.dll 7.00.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\ntmarta.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Program Files\Zune\ZuneDB.dll 4.8.2345.0
C:\Program Files\Zune\ZuneSE.dll 4.8.2345.0
C:\Program Files\Zune\ZuneQP.dll 4.8.2345.0
C:\Windows\system32\XmlLite.dll 1.3.1000.0
C:\Windows\system32\LINKINFO.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\apphelp.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\NetworkExplorer.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\ntshrui.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\cscapi.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\slc.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MPR.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\WINSTA.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\windowscodecsext.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\msxml6.dll 6.30.7601.17514
C:\Windows\system32\mscms.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\icm32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\dfscli.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WtsApi32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\UIAutomationProvider\427b7ac4bbe49410e494979928d9b560\UIAutomationProvider.ni.dll 3.0.6920.4902 built by: NetFXw7
C:\Windows\assembly\NativeImages_v2.0.50727_64\Accessibility\23ea8465ac746c69a6ed7fdf628d3e9c\Accessibility.ni.dll 2.0.50727.4927 (NetFXspW7.050727-4900)
C:\Windows\system32\mlang.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.ServiceModel#\667a561422e2ccf10daef0a5dc6c8043\System.ServiceModel.Web.ni.dll 3.5.594.5420
C:\Windows\assembly\NativeImages_v2.0.50727_64\SMDiagnostics\c268879bbddc814fadfe497300c03752\SMDiagnostics.ni.dll 3.0.4506.5420 (Win7SP1.030729-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.ServiceModel\962330ba0685ac1176b611bc052d0ca7\System.ServiceModel.ni.dll 3.0.4506.5420 (Win7SP1.030729-5400)
C:\Windows\system32\AVIFIL32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSACM32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSVFW32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Deployment\e2a96543efb1769b60dc0ff9e292c4bb\System.Deployment.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\ad884485b63f08acfaf791d2dfaadd32\System.Drawing.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\0737590c91350bf9ce7416cbbf789bc7\System.Windows.Forms.ni.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\system32\pcwum.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\perfcounter.dll 4.0.30319.1 (RTMRel.030319-0100)
C:\Windows\system32\MSVCR100_CLR0400.dll 10.00.30319.1
C:\Windows\system32\pdh.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\aspnet_counters.dll 4.0.30319.1 (RTMRel.030319-0100)
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_perf.dll 4.0.30319.1 (RTMRel.030319-0100)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\aspnet_perf.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Program Files\Microsoft SQL Server\100\Shared\instapi10.dll 2009.0100.1600.01 ((KJ_RTM).100402-1539 )
C:\Windows\system32\BROWCLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\SAMCLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\LOGONCLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\System32\perfos.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll 8.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\System32\drprov.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\ntlanman.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\davclnt.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\System32\DAVHLPR.dll 6.1.7600.16385 (win7_rtm.090713-1255)

**Comment by leetreveil** [comment]
A fix for this will be available in the next version.
