### ISSUE TITLE
Something bad happened

### ISSUE THREAD

**Issue by ghost** [leetreveil/Zune-Social-Tagger#11]
Happens when trying to select "Scan All". Tried both elevated and non. Here's the error report. Thanks for the work, dude.

Application:       Zune Social Tagger
Version:           2.4.1.0
Date:              11/09/2011 11:55:38
Computer name:     SHERRI-PC
User name:         Brian
OS:                Microsoft Windows NT 6.1.7601 Service Pack 1
Culture:           en-US
System up time:    15:53:22.8280000
App up time:       00:00:51.5634658
Total memory:      4094Mb
Available memory:  2268Mb

Exception classes:  
   System.ArgumentOutOfRangeException
Exception messages: 
   Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack Traces:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ZuneSocialTagger.GUI.ViewsViewModels.WebAlbumList.WebAlbumListViewModel.ScanChunk(List`1 toScan, Int32 position, Int32 albumsTotal)
   at GalaSoft.MvvmLight.Command.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
Loaded Modules:
C:\Program Files\Zune\Zune Social Tagger.exe 2.4.1.0
C:\Windows\SYSTEM32\ntdll.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\SYSTEM32\MSCOREE.DLL 4.0.40305.0 (Main.040305-0000)
C:\Windows\system32\KERNEL32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\KERNELBASE.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\ADVAPI32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\msvcrt.dll 7.0.7600.16385 (win7_rtm.090713-1255)
C:\Windows\SYSTEM32\sechost.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\RPCRT4.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\SHLWAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\GDI32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\USER32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\LPK.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\USP10.dll 1.0626.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\IMM32.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSCTF.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.4940_none_88df89932faf0bf6\MSVCR80.dll 8.00.50727.4940
C:\Windows\system32\shell32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\ole32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\profapi.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\mscorlib\8f7abb6f7384aad8fc43659820726eab\mscorlib.ni.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\system32\CRYPTBASE.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\uxtheme.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System\3e6eefab37b44e147db80a3c34f0ac05\System.ni.dll 2.0.50727.5447 (Win7SP1GDR.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\WindowsBase\64fc9675d94bda9f45731097f140c4f6\WindowsBase.ni.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationCore\72ea2b7db0ac2d9407d8ab2ed257c62a\PresentationCore.ni.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\90e096ee99f6b0760c47016f862cf5a8\PresentationFramework.ni.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\Microsoft.NET\Framework64\v3.0\WPF\wpfgfx_v0300.dll 3.0.6920.5011 built by: Win7SP1
C:\Windows\system32\OLEAUT32.dll 6.1.7601.17567
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Core\5f7c48b31971fee1af48dd20c7dd7033\System.Core.ni.dll 3.5.30729.5420 built by: Win7SP1
C:\Windows\system32\dwmapi.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\CRYPTSP.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rsaenh.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\VERSION.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\shfolder.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\df2bfb30ffdbfbb49d2c5ef6fc763578\System.Configuration.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\318b11a6b944c9ef2998d374c9d5bda8\System.Xml.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\system32\urlmon.dll 8.00.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WININET.dll 8.00.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\iertutil.dll 8.00.7601.17638 (win7sp1_gdr.110620-1602)
C:\Windows\system32\CRYPT32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSASN1.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\WindowsCodecs.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\d3d9.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\d3d8thk.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\aticfx64.dll 8.17.10.1077
C:\Windows\system32\atiu9p64.dll 8.14.01.6210
C:\Windows\system32\atiumd64.dll 7.14.10.0833
C:\Windows\system32\atiumd6a.dll 8.14.10.0308
C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\e197484e00ac02ef81220d0c8b6491e1\PresentationFramework.Aero.ni.dll 3.0.6920.4902 built by: NetFXw7
C:\Windows\system32\WINMM.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\PresentationNative_v0300.dll 3.0.6920.4902 built by: NetFXw7
C:\Windows\system32\CLBCatQ.DLL 2001.12.8530.16385 (win7_rtm.090713-1255)
C:\Windows\system32\RpcRtRemote.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\msctfui.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Seri#\50faf7f472bfc6d562696341df45b3c9\System.Runtime.Serialization.ni.dll 3.0.4506.5420 (Win7SP1.030729-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml.Linq\ebd55d35d25cf10e6e24453238d3c5eb\System.Xml.Linq.ni.dll 3.5.30729.5420 built by: Win7SP1
C:\Windows\system32\rasapi32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rasman.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WS2_32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\NSI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rtutils.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\mswsock.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\wshtcpip.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\wship6.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\winhttp.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\webio.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\IPHLPAPI.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WINNSI.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\dhcpcsvc.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\dhcpcsvc6.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\SspiCli.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\credssp.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\CFGMGR32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\DNSAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDNSP.DLL 6.500.3165.0
C:\Windows\system32\PSAPI.DLL 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\rasadhlp.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\System32\fwpuclnt.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\assembly\NativeImages_v2.0.50727_64\ZuneDBApi\344916fd10e9ab1809105b8582c24cbd\ZuneDBApi.ni.dll 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorsec.dll 2.0.50727.4927 (NetFXspW7.050727-4900)
C:\Windows\system32\WINTRUST.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.17514_none_a4d6a923711520a9\COMCTL32.dll 5.82 (win7_rtm.090713-1255)
C:\Windows\system32\security.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\SECUR32.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\imagehlp.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\schannel.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\ncrypt.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\bcrypt.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\bcryptprimitives.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\USERENV.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\GPAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\cryptnet.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WLDAP32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\SensApi.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\Cabinet.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\DEVRTL.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Program Files\Zune\ZuneDBApi.dll 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_08e4299fa83d7e3c\MSVCR90.dll 9.00.30729.4940
C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4940_none_08e4299fa83d7e3c\msvcm90.dll 9.00.30729.4940
C:\Program Files\Zune\ZuneCfg.DLL 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Program Files\Zune\ZuneNativeLib.dll 4.8.2345.0 (ZUNE_DORADO_V4.8_RTM.110805-1156)
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_2b24536c71ed437a\gdiplus.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\SETUPAPI.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\DEVOBJ.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\NETAPI32.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\netutils.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\srvcli.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\wkscli.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_fa396087175ac9ac\comctl32.dll 6.10 (win7_rtm.090713-1255)
C:\Windows\system32\propsys.dll 7.00.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\ntmarta.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Program Files\Zune\ZuneDB.dll 4.8.2345.0
C:\Program Files\Zune\ZuneSE.dll 4.8.2345.0
C:\Program Files\Zune\ZuneQP.dll 4.8.2345.0
C:\Windows\system32\ntshrui.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\cscapi.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\slc.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\AVIFIL32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSACM32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\MSVFW32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WtsApi32.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\WINSTA.dll 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\assembly\NativeImages_v2.0.50727_64\UIAutomationProvider\427b7ac4bbe49410e494979928d9b560\UIAutomationProvider.ni.dll 3.0.6920.4902 built by: NetFXw7
C:\Windows\assembly\NativeImages_v2.0.50727_64\Accessibility\23ea8465ac746c69a6ed7fdf628d3e9c\Accessibility.ni.dll 2.0.50727.4927 (NetFXspW7.050727-4900)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\ad884485b63f08acfaf791d2dfaadd32\System.Drawing.ni.dll 2.0.50727.5420 (Win7SP1.050727-5400)
C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\0737590c91350bf9ce7416cbbf789bc7\System.Windows.Forms.ni.dll 2.0.50727.5446 (Win7SP1GDR.050727-5400)
C:\Windows\system32\pcwum.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\perfcounter.dll 2.0.50727.4927 (NetFXspW7.050727-4900)
C:\Windows\system32\pdh.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\system32\BROWCLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\SAMCLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\system32\LOGONCLI.DLL 6.1.7601.17514 (win7sp1_rtm.101119-1850)
C:\Windows\System32\perfos.dll 6.1.7600.16385 (win7_rtm.090713-1255)
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll 8.0.50727.5420 (Win7SP1.050727-5400)

**Comment by leetreveil** [comment]
Is this happening at the very end of scan all?

**Comment by ghost** [comment]
No, it happens right after I click on it.

**Comment by leetreveil** [comment]
Ok I think i've fixed the problem, can you retest after the next update.

**Comment by ghost** [comment]
Will do. Thanks.

Sent from my Windows Phone

-----Original Message-----
