### ISSUE TITLE
Provide a build of the latest version?

### ISSUE THREAD

**Issue by factormystic** [leetreveil/Zune-Social-Tagger#13]
I'd be much appreciated so I don't have to track down and build the external dependencies.

**Comment by leetreveil** [comment]
The latest version (2.4.2) is out on the downloads page now.

**Comment by factormystic** [comment]
All I'm seeing on the downloads page is source zips... do those also have binaries somewhere inside?

**Comment by leetreveil** [comment]
https://github.com/leetreveil/Zune-Social-Tagger/downloads not there?

**Comment by factormystic** [comment]
Well yes as I said I see the zip files (http://i.imgur.com/z4XmD.png -- same as logged in) but I'm not seeing any direct links to binary builds

**Comment by leetreveil** [comment]
You want to download the zip files below 'Download Packages', there is an installer in there.

**Comment by factormystic** [comment]
Haha... _now_ it does. Thanks!
