### ISSUE TITLE
Marketplace not available in my area?

### ISSUE THREAD

**Issue by The-Frederick** [leetreveil/Zune-Social-Tagger#14]
When I try to use the ZST, it tells me that the marketplace not available in my area (Australia), even though it now is.

**Comment by leetreveil** [comment]
There's a marketplace in Australia but there's no music, only videos and apps.

**Comment by The-Frederick** [comment]
They added music recently actually. :P

**Comment by leetreveil** [comment]
Fixed in latest update.

**Comment by The-Frederick** [comment]
Cool, thanks. :)
