### ISSUE TITLE
ZST links Albums perfectly but does not link individual songs in the album. When i like click on More about this album it takes me to correct album but besides the songs 'in collection' is not shown. Screenshots: 

### ISSUE THREAD

**Issue by ghost** [leetreveil/Zune-Social-Tagger#16]
![1](https://f.cloud.github.com/assets/5254545/982460/1c20f106-07f3-11e3-9a77-e1065bb48297.png)
![3](https://f.cloud.github.com/assets/5254545/982447/4355c910-07f1-11e3-901e-a57be1bb7ff0.png)
![4](https://f.cloud.github.com/assets/5254545/982448/475944a6-07f1-11e3-9684-2fa039888ac1.png)
![Uploading 1.png . . .]()

**Comment by noms23** [comment]
same thing happens to me, i have this album in my collection, and when i click the more info about this album, it does not shows "IN COLLECTION"
