### ISSUE TITLE
Can't link albums.

### ISSUE THREAD

**Issue by The-Frederick** [leetreveil/Zune-Social-Tagger#2]
When I try to link an album, it seemingly doesn't connect to the online db and it tells me that no results have been found. I'm not in the US, so it could be a problem connecting to the Marketplace.

**Comment by leetreveil** [comment]
Which region are you in? The app uses the same online database as the zune software. So i'm curious to understand whats going on.

**Comment by The-Frederick** [comment]
I'm in Australia. I can't access the music section of the Marketplace through the Zune software, so it could be something related to that.

**Comment by leetreveil** [comment]
That is why, if you cant access the marketplace through the zune software you wont be able to through the zune social tagger. There's a workaround to this you can set your regional settings on your computer to 'United States', this will give you access the the american marketplace.

**Comment by The-Frederick** [comment]
Hi mate,

I changed my region to US, and the ZST worked once. But now I'm trying it again and it's back to not working, even thought my PC region is US.

**Comment by leetreveil** [comment]
When is it crashing?

**Comment by The-Frederick** [comment]
It's not crashing. It's just not connecting the the marketplace.

**Comment by leetreveil** [comment]
Even searching for 'U2' doesn't work?

**Comment by The-Frederick** [comment]
Nope, it always comes up with no results. And albums that are already tagged all come up as "Unavailable".
