### ISSUE TITLE
Wrong artist info

### ISSUE THREAD

**Issue by hamada717** [leetreveil/Zune-Social-Tagger#3]
After i Linked one of Eminem's albums with the corresponding album, the artist background in the phone for all eminem songs is lil wayne's. zune shows the lil wayne page too when i click "more about Eminem".i tried delinking all eminem albums and relinking them again, i even reset the phone and still no hope. Is that a zune or a zune social tagger issue?
Thank you.

**Comment by leetreveil** [comment]
Hi, this is a Zune issue. ZST does not have the ability to change who an artist is linked to. (unfortunately)

**Comment by hamada717-duplicate** [comment]
Okai thanks.
