### ISSUE TITLE
2.3 and 2.3.1 Version not Working at all.

### ISSUE THREAD

**Issue by edgar89** [leetreveil/Zune-Social-Tagger#4]
Hi. I'm from Italy and since I got my WP7 I used Zune Social Tagger 2.2 to link album/artists/etc and I had no problem at all. Since yesterday when I come back from easter holydays I was prompted to upgrade to 2.3.1 and I did it.

Since this upgrade though , no action is possible; "Scan All" button is grey, right click-> link does not work (0 results) and all previously linked albums are now unlinked. If I uninstall 2.3.1 and install again 2.2 all albums come back on linked status and everything works fine.

This is a screenshot showing the program as i see it:

http://img838.imageshack.us/img838/5446/zst231.png (2.3.1)
http://img864.imageshack.us/img864/8724/zst22.png (2.2)

OS is Windows 7 Professional SP1 Italian, x64 with all security updates installed. Zune Marketplace is Italian and access through zune software works just fine. More over, even if 2.3.1 seems not to work previously made linkings works well and in zune marketplace still exists the "more on..." menu option.

I'm now back on 2.2 but i hope you can solve the issue asap

Greetings for the program anyway ;)
edgar89

**Comment by leetreveil** [comment]
Hi, I have pulled the 2.3.1 release. Stay on 2.2 until I release a new update that fixes these issues for you.
