### ISSUE TITLE
Frame Size Error

### ISSUE THREAD

**Issue by ahugh** [leetreveil/Zune-Social-Tagger#5]
I'm getting an error when I try to link some of my songs.  The message appears at the bottom of the application and says

"Specified frame size 2385023 exceeds actual frame size 604076"

Some of my other songs also get the same error with different sizes.

I'm using version 2.2

**Comment by leetreveil** [comment]
This will be a bug in the library I use for ZST (https://github.com/saitodisse/id3tag.net). It would be very helpful if you could email me the audio file that is causing the problems to leetreveil at gmail dot com. Thanks.
