### ISSUE TITLE
Multiple problems with ZST

### ISSUE THREAD

**Issue by efady** [leetreveil/Zune-Social-Tagger#6]
Hi leetreveil,

I first wanted to thank you for your software, which looks amazing, and does exactly what I was expecting to enjoy even more my WP7 user experience.
Unfortunatelly, I however encountered several issues using Zune Social Tagger, and none of my albums can sync with the Marketplace.

I made a quick video showing the problems here : http://www.youtube.com/watch?v=HVLf0I2iCD8

If that can help you in your investigation, I'm currently running Windows 7 through BootCamp on my Mid-2009 MBP, and the MP3 files are copied from my original iTunes Database, on Mac OS.

Thanks !

**Comment by leetreveil** [comment]
Thanks for the video. The most interesting problem is you not getting any
search results. Could I get some background info on your location?

Where do you live?
What value is set in the 'location' tab on Region and Laguage on the Control
Panel.
Do you get search results in the zune software?

The other problems are related to the tagging library I am using. I have my
eye on another library that is more mature. In the mean time you could try
re-tagging the files with mp3tag to fix those files.

Thanks, Lee

**Comment by efady** [comment]
Actually, I live in France, in Paris' suburb.
Yes, I do get results through Marketplace, but the fun part is when using Zune Social Tagger 2.2, I can get results wheareas switching to 2.3 removes all of them. 
Also, I can't just use 2.2 : when linking albums, ZST crashes and nothing is saved. 

I'll give you other details as soon as I come back home ;-)

Thanks a lot !

**Comment by efady** [comment]
I retried using ver 2.2, nothing more...

Also, my location tab in control panel is disabled, but I live in France ; there's no reason why I couldn't get info from the Marketplace...

My tags are perfectly matching the ones from the Marketplace, but I cant' get any result.

Do you have any idea ? 
Thanks

**Comment by leetreveil** [comment]
Interesting that the location tab in the control panel is disabled. ZST
reads your location info from that tab.

http://images.knowhow.com/Computing/keyboard-region.png

How does it look compared to that image?

**Comment by efady** [comment]
Oh, I was not talking about the right one then :P

I mistook because of the control panel : when you search "Location" in the Search field, you end up in a menu with location through GPS ;-)

This one says "France" :D

**Comment by leetreveil** [comment]
This bug has been fixed in version 2.3.4. You can download it now.

**Comment by efady** [comment]
Thanks a lot leetreveil, now everything is working perfectly fine !

Thanks for creating such an amazing software, and keep going ! ;-)
