### ISSUE TITLE
ZST 2.3.3 and 2.3.4 Issue with album artwork

### ISSUE THREAD

**Issue by JayTee-zz** [leetreveil/Zune-Social-Tagger#7]
Lee:

Like many, I use your fantastic software (and have for well over a year now) and love it. It's the only thing that accurately tags everything for full compatibility with the Zune Marketplace.

My issue is a relatively minor one. In versions 2.3.3 as well as 2.3.4, copying the album artwork in the song/tag select screen results in a blank file. It simply doesn't copy anything (i.e., nothing is able to be pasted into the zune album art). In the final screen (where everything is reported as "now linked" to the Zune marketplace), no album art shows up at all, thus nothing is able to be copied.

When I return to version 2.2, everything works fine.  Any ideas?

**Comment by leetreveil** [comment]
Hi there, thanks for the report! I have found the bug and the fix will come in the next version.

**Comment by JayTee-zz** [comment]
Wow! Thanks for the update, Lee.
