### ISSUE TITLE
When running a 'scan all' complains of hitting break point

### ISSUE THREAD

**Issue by ctolkien** [leetreveil/Zune-Social-Tagger#9]
<img src="http://i.imgur.com/zk45R.png" />

**Comment by leetreveil** [comment]
Once I release the next version of ZST can you let me know if this error still exists?

**Comment by ctolkien** [comment]
Problem persists with 2.4.1

**Comment by leetreveil** [comment]
I can't reproduce this error. Googling isn't helping either. Is there any more information you can give me?

**Comment by leetreveil** [comment]
Fixed in commit 4d2d9b6
